version: '3'
services:

  lenses:
    image: lensesio/box
    container_name: lenses
    restart: always
    environment:
      EULA: "${LICENSE}"
    networks:
      - lenses-box
    ports:
      - 3030:3030

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=lenses-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    cap_add:
      - IPC_LOCK
    networks:
      - lenses-box
    ports:
      - 9200:9200
      - 9300:9300

networks:
  lenses-box:
    driver: bridge

